[package]
name = "qcl"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
description = "Model checker and inference engine for Quantified Coalition Logic"

[workspace]

[dependencies]
bit-set = "0.11.1"
linenoise-rust = "0.2.1"
thiserror = "2"

[patch.crates-io]
linenoise-rust = { path = "vendor/linenoise-rust" }

[dev-dependencies]
pretty_assertions = "1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
