apiVersion: v1
kind: ServiceAccount
metadata:
  name: safeops-executor
  namespace: safeops-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: safeops-executor
  namespace: safeops-demo
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safeops-executor
  namespace: safeops-demo
subjects:
  - kind: ServiceAccount
    name: safeops-executor
    namespace: safeops-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: safeops-executor
